### ISSUE TITLE
Is it possible to run this demo on Raspbian (Raspberry Pi)?

### ISSUE THREAD

**Issue by xzhng120** [openfmb/openfmb-dds-demo#2]
Hi Andre,

I have noticed the DDS library provided is x64, is it possible to compile this demo for ARM architecture so that it runs on Raspberry Pi? Thanks

**Comment by andre-rti** [comment]
Hi Xzhng,

The demo should build for the Raspberry Pi. I have not tried it yet but 
I don't see why not. As far as the DDS libraries you can get libraries 
for the Raspberry Pi here 
https://community.rti.com/downloads/rti-connext-dds-raspberry-pi. 
However those libraries will not include DDS secure. I think it should 
just run without the security features turned on. If not you may need to 
remove the security related configuration in the USER_QOS_PROFILES.xml 
file. If you would like DDS secure libraries please contact your local 
account team. See https://www.rti.com/company/contact for the contact 
information.

Andre

**Comment by xzhng120** [comment]
Thanks for the info. You're right. Now I get the error of not finding libnddssecurity.so
The available library on RTI doesn't have the secure.

and I tried to find the USER_QOS_PROFILES.xml for QoS but all the files seem to be associated with RTI demos in resource/template/rti_workspace/examples

**Comment by xzhng120** [comment]
Thanks for the info. You're right. Now I get the error of not finding libnddssecurity.so
The available library on RTI doesn't have the secure.

and I tried to find the USER_QOS_PROFILES.xml for QoS but all the files seem to be associated with RTI demos in resource/template/rti_workspace/examples

Could you point me to the correct file(s) to de-select RTI Secure?

Thanks

**Comment by andre-rti** [comment]
in scripts/USER_QOS_PROFILES.xml remove the participant properties. Attached is a USER_QOS_PROFILES.xml file which does not have security enabled and should work with non-secure communication. 


If you want to change the file manually you need to remove all the properties sections related to security configuration as follow: 




        <property>
          <value>
            <element>
              <name>com.rti.serv.load_plugin</name>
              <value>com.rti.serv.secure</value>
            </element>
            <element>
              <name>com.rti.serv.secure.library</name>
              <value>nddssecurity</value>
            </element>
            <element>
              <name>com.rti.serv.secure.create_function</name>
              <value>RTI_Security_PluginSuite_create</value>
            </element>
            <element>
              <name>com.rti.serv.secure.logging.log_level</name>
              <value>2</value>
            </element>
            <element>
              <name>com.rti.serv.secure.authentication.ca_file</name>
              <value>../cert/RTI_OPENFMB_DEMO_CA_CERT.pem</value>
            </element>
            <element>
              <name>com.rti.serv.secure.access_control.permissions_authority_file</name>
              <value>../cert/RTI_OPENFMB_DEMO_CA_CERT.pem</value>
            </element>
            <element>
              <name>com.rti.serv.secure.authentication.certificate_file</name>
              <value>../cert/RTI_OPENFMB_DEMO_PEER_CERT.pem</value>
            </element>
            <element>
              <name>com.rti.serv.secure.authentication.private_key_file</name>
              <value>../cert/RTI_OPENFMB_DEMO_PEER_KEY.pem</value>
            </element>
            <element>
              <name>com.rti.serv.secure.access_control.governance_file</name>
              <value>../cert/RTI_OPENFMB_DEMO_GOVERNANCE.p7s</value>
            </element>
          </value>
        </property>

And also remove the permissions file section in each profile. For example for the Solar_Profile_Reading remove
        <property>
          <value>
            <element>
              <name>com.rti.serv.secure.access_control.permissions_file</name>
              <value>../cert/RTI_OPENFMB_DEMO_SOLAR_PERMISSIONS.p7s</value>
            </element>
          </value>
        </property>

**Comment by andre-rti** [comment]
Here is the file. I renamed from .xml  to .txt
[USER_QOS_PROFILES.txt](https://github.com/openfmb/openfmb-dds-demo/files/1842531/USER_QOS_PROFILES.txt)

**Comment by xzhng120** [comment]
Thank you very much Andre

I can run ./simgo on my Pi now!

**Comment by andre-rti** [comment]
Awesome!!! Good to know it works.
